baseURL = "https://www.tsbrown.net/"
languageCode = "en-us"
title = "Thomas Brown"
theme = "hugo-initio"
publishDir = "Public"

[params]
    name = "Thomas Brown"
    description = "Data Scientist and Statistician"
    email = ""
    phone = ""
    address = ""
    year = 2019
    background = ""
    favicon = "images/gt_favicon.png"
    #DateForm = "January 2, 2006"
    DateForm = ""

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
    
#[[menu.main]]
#    name = "blog"
#    url = "/post/"
#    weight = 5

#[[menu.main]]
#    name = "CV"
 #   weight = 5
##    url = "/cv/"

#[params.disqus]
#    site = "hugo-initio-site.disqus.com"

#[params.sharethis]
#    property = "123456789012345678901234"
#    custom = true

[params.google.analytics]
    trackerID = "UA-109464939-1"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fa-facebook-square"
    footer = false
    sharethis = false
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fa-twitter-square"
    footer = false
    sharethis = false
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = false
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/tomsouthwellbrown/"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/T-S-Brown"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:tom@tsbrown.net"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"
